### ISSUE TITLE
Support for non square crops

### ISSUE THREAD

**Issue by naltatis** [github/image-crop-element#11]
The component works great, but I'd like to be able to set a custom aspect ratio for the crop. This is currently not possible, right? Or am I missing an option?

**Comment by muan** [comment]
That is right. It was an intentional decision to not support custom aspect ratio to keep this element as simple as possible.

**Comment by naltatis** [comment]
Ok, thanks for your response!

**Comment by kapouer** [comment]
That's a bit weird, though... it makes the lib useless for most cases. Maybe it should be advertised somewhere in the README ?
