### ISSUE TITLE
Shane wants to crop a image 

### ISSUE THREAD

**Issue by ItsShAneSeyhanRohde** [github/image-crop-element#34]
Hi it’s Shane Seyhan Rohde How do I flip it over
![image](https://user-images.githubusercontent.com/78567159/106962048-57bca900-66f3-11eb-8b08-6142d2f6cc93.jpg)
How

**Comment by koddsson** [comment]
Hi Shane!

The image crop element doesn't have any flip mechanism so you're going to have to flip the image on your computer before uploading.
